/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from; 
 */

#ifndef _SYS_SYSCALL_H_
#define _SYS_SYSCALL_H_

#define a_SYS_syscall   0
#define a_SYS_exit      1
#define a_SYS_fork      2
#define a_SYS_read      3
#define a_SYS_write     4
#define a_SYS_old_open  5       /* 5 is old open */
#define a_SYS_close     6
#define a_SYS_wait4     7
#define a_SYS_old_creat 8       /* 8 is old creat */
#define a_SYS_link      9
#define a_SYS_unlink    10
#define a_SYS_execv     11
#define a_SYS_chdir     12
#define a_SYS_fchdir    13
#define a_SYS_mknod     14
#define a_SYS_chmod     15
#define a_SYS_chown     16
#define a_SYS_obreak    17
#define a_SYS_getfsstat 18
#define a_SYS_lseek     19
#define a_SYS_getpid    20
#define a_SYS_mount     21
#define a_SYS_unmount   22
#define a_SYS_setuid    23
#define a_SYS_getuid    24
#define a_SYS_exec_with_loader  25
#define a_SYS_ptrace    26
#ifdef  COMPAT_43
#define a_SYS_nrecvmsg  27
#define a_SYS_nsendmsg  28
#define a_SYS_nrecvfrom 29
#define a_SYS_naccept   30
#define a_SYS_ngetpeername      31
#define a_SYS_ngetsockname      32
#else
#define a_SYS_recvmsg   27
#define a_SYS_sendmsg   28
#define a_SYS_recvfrom  29
#define a_SYS_accept    30
#define a_SYS_getpeername       31
#define a_SYS_getsockname       32
#endif
#define a_SYS_access    33
#define a_SYS_chflags   34
#define a_SYS_fchflags  35
#define a_SYS_sync      36
#define a_SYS_kill      37
#define a_SYS_old_stat  38      /* 38 is old stat */
#define a_SYS_setpgid   39
#define a_SYS_old_lstat 40      /* 40 is old lstat */
#define a_SYS_dup       41
#define a_SYS_pipe      42
#define a_SYS_set_program_attributes    43
#define a_SYS_profil    44
#define a_SYS_open      45
                                /* 46 is obsolete osigaction */
#define a_SYS_getgid    47
#define a_SYS_sigprocmask       48
#define a_SYS_getlogin  49
#define a_SYS_setlogin  50
#define a_SYS_acct      51
#define a_SYS_sigpending        52
#define a_SYS_classcntl 53
#define a_SYS_ioctl     54
#define a_SYS_reboot    55
#define a_SYS_revoke    56
#define a_SYS_symlink   57
#define a_SYS_readlink  58
#define a_SYS_execve    59
#define a_SYS_umask     60
#define a_SYS_chroot    61
#define a_SYS_old_fstat 62      /* 62 is old fstat */
#define a_SYS_getpgrp   63
#define a_SYS_getpagesize       64
#define a_SYS_mremap    65
#define a_SYS_vfork     66
#define a_SYS_stat      67
#define a_SYS_lstat     68
#define a_SYS_sbrk      69
#define a_SYS_sstk      70
#define a_SYS_mmap      71
#define a_SYS_ovadvise  72
#define a_SYS_munmap    73
#define a_SYS_mprotect  74
#define a_SYS_madvise   75
#define a_SYS_old_vhangup       76      /* 76 is old vhangup */
#define a_SYS_kmodcall  77
#define a_SYS_mincore   78
#define a_SYS_getgroups 79
#define a_SYS_setgroups 80
#define a_SYS_old_getpgrp       81      /* 81 is old getpgrp */
#define a_SYS_setpgrp   82
#define a_SYS_setitimer 83
#define a_SYS_old_wait  84      /* 84 is old wait */
#define a_SYS_table     85
#define a_SYS_getitimer 86
#define a_SYS_gethostname       87
#define a_SYS_sethostname       88
#define a_SYS_getdtablesize     89
#define a_SYS_dup2      90
#define a_SYS_fstat     91
#define a_SYS_fcntl     92
#define a_SYS_select    93
#define a_SYS_poll      94
#define a_SYS_fsync     95
#define a_SYS_setpriority       96
#define a_SYS_socket    97
#define a_SYS_connect   98
#ifdef  COMPAT_43
#define a_SYS_accept    99
#else
#define a_SYS_old_accept        99      /* 99 is old accept */
#endif
#define a_SYS_getpriority       100
#ifdef  COMPAT_43
#define a_SYS_send      101
#define a_SYS_recv      102
#else
#define a_SYS_old_send  101     /* 101 is old send */
#define a_SYS_old_recv  102     /* 102 is old recv */
#endif
#define a_SYS_sigreturn 103
#define a_SYS_bind      104
#define a_SYS_setsockopt        105
#define a_SYS_listen    106
#define a_SYS_plock     107
#define a_SYS_old_sigvec        108     /* 108 is old sigvec */
#define a_SYS_old_sigblock      109     /* 109 is old sigblock */
#define a_SYS_old_sigsetmask    110     /* 110 is old sigsetmask */
#define a_SYS_sigsuspend        111
#define a_SYS_sigstack  112
#ifdef  COMPAT_43
#define a_SYS_recvmsg   113
#define a_SYS_sendmsg   114
#else
#define a_SYS_old_recvmsg       113     /* 113 is old recvmsg */
#define a_SYS_old_sendmsg       114     /* 114 is old sendmsg */
#endif
                                /* 115 is obsolete vtrace */
#define a_SYS_gettimeofday      116
#define a_SYS_getrusage 117
#define a_SYS_getsockopt        118
#define a_SYS_readv     120
#define a_SYS_writev    121
#define a_SYS_settimeofday      122
#define a_SYS_fchown    123
#define a_SYS_fchmod    124
#ifdef  COMPAT_43
#define a_SYS_recvfrom  125
#else
#define a_SYS_old_recvfrom      125     /* 125 is old recvfrom */
#endif
#define a_SYS_setreuid  126
#define a_SYS_setregid  127
#define a_SYS_rename    128
#define a_SYS_truncate  129
#define a_SYS_ftruncate 130
#define a_SYS_flock     131
#define a_SYS_setgid    132
#define a_SYS_sendto    133
#define a_SYS_shutdown  134
#define a_SYS_socketpair        135
#define a_SYS_mkdir     136
#define a_SYS_rmdir     137
#define a_SYS_utimes    138
                                /* 139 is obsolete 4.2 sigreturn */
#define a_SYS_adjtime   140
#ifdef  COMPAT_43
#define a_SYS_getpeername       141
#else
#define a_SYS_old_getpeername   141     /* 141 is old getpeername */
#endif
#define a_SYS_gethostid 142
#define a_SYS_sethostid 143
#define a_SYS_getrlimit 144
#define a_SYS_setrlimit 145
#define a_SYS_old_killpg        146     /* 146 is old killpg */
#define a_SYS_setsid    147
#define a_SYS_quotactl  148
#define a_SYS_oldquota  149
#ifdef  COMPAT_43
#define a_SYS_getsockname       150
#else
#define a_SYS_old_getsockname   150     /* 150 is old getsockname */
#endif
#define a_SYS_pread     151
#define a_SYS_pwrite    152
#define a_SYS_pid_block 153
#define a_SYS_pid_unblock       154
#define a_SYS_signal_urti       155
#define a_SYS_sigaction 156
#define a_SYS_sigwaitprim       157
#define a_SYS_nfssvc    158
#define a_SYS_getdirentries     159
#define a_SYS_statfs    160
#define a_SYS_fstatfs   161
#define a_SYS_async_daemon      163
#define a_SYS_getfh     164
#define a_SYS_getdomainname     165
#define a_SYS_setdomainname     166
#define a_SYS_exportfs  169
#define a_SYS_alt_plock 181     /* 181 is alternate plock */
#define a_SYS_getmnt    184
#define a_SYS_alt_sigpending    187     /* 187 is alternate sigpending */
#define a_SYS_alt_setsid        188     /* 188 is alternate setsid */
#define a_SYS_swapon    199
#define a_SYS_msgctl    200
#define a_SYS_msgget    201
#define a_SYS_msgrcv    202
#define a_SYS_msgsnd    203
#define a_SYS_semctl    204
#define a_SYS_semget    205
#define a_SYS_semop     206
#define a_SYS_uname     207
#define a_SYS_lchown    208
#define a_SYS_shmat     209
#define a_SYS_shmctl    210
#define a_SYS_shmdt     211
#define a_SYS_shmget    212
#define a_SYS_mvalid    213
#define a_SYS_getaddressconf    214
#define a_SYS_msleep    215
#define a_SYS_mwakeup   216
#define a_SYS_msync     217
#define a_SYS_signal    218
#define a_SYS_utc_gettime       219
#define a_SYS_utc_adjtime       220
#define a_SYS_security  222
#define a_SYS_kloadcall 223
#define a_SYS_new_stat      224 /* Runs with OSF5 */
#define a_SYS_new_lstat     225 /* Runs with OSF5 */
#define a_SYS_new_fstat     226 /* Runs with OSF5 */
#define a_SYS_new_statfs    227 /* Runs with OSF5 */
#define a_SYS_getpgid   233
#define a_SYS_getsid    234
#define a_SYS_sigaltstack       235
#define a_SYS_waitid    236
#define a_SYS_priocntlset       237
#define a_SYS_sigsendset        238
#define a_SYS_set_speculative   239
#define a_SYS_msfs_syscall      240
#define a_SYS_sysinfo   241
#define a_SYS_uadmin    242
#define a_SYS_fuser     243
#define a_SYS_proplist_syscall  244
#define a_SYS_ntp_adjtime       245
#define a_SYS_ntp_gettime       246
#define a_SYS_pathconf  247
#define a_SYS_fpathconf 248
#define a_SYS_uswitch   250
#define a_SYS_usleep_thread     251
#define a_SYS_audcntl   252
#define a_SYS_audgen    253
#define a_SYS_sysfs     254
#define a_SYS_subsys_info       255
#define a_SYS_getsysinfo        256
#define a_SYS_setsysinfo        257
#define a_SYS_afs_syscall       258
#define a_SYS_swapctl   259
#define a_SYS_memcntl   260
#define a_SYS_fdatasync 261
/* Added by Hung-Wei */
#define linux_times		323
#define linux_alpha_uname	339
#define linux_mremap		341
#define linux_gettimeofday	359
#define rt_sigaction		352
#define linux_getrusage		364
#define linux_exit_group	405
#define linux_alpha_stat64	425
#define linux_alpha_fstat64	427
#define FIRST   0
#define LAST    438

#define FIRST   0
#define LAST    438

#endif  /* _SYS_SYSCALL_H_ */
